services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fraolbmax/guzolink-backend:latest
    container_name: guzolink-backend
    restart: unless-stopped

    env_file:
      - ./backend/.env.production

    depends_on:
      - mongodb

    ports:
      - "127.0.0.1:5000:5000"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5003/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: fraolbmax/guzolink-frontend:latest
    container_name: guzolink-frontend
    restart: unless-stopped

    env_file:
      - ./frontend/.env.local

    depends_on:
      - backend

    ports:
      - "127.0.0.1:3000:80"

  mongodb:
    image: mongo:latest
    container_name: guzolink-mongodb
    restart: unless-stopped

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
